trigger: 'none'

jobs:
- job: Webapp
  displayName: 'Build Web App'
pool:
  vmImage: windows-2019
variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core sdk'
  inputs:
    packageType: 'sdk'
    version: '6.0.100'
- task: DotNetCoreCLI@2
  displayName: Restore-Nuget-Packages
  inputs:
    command: 'restore'
    projects: '**/WebApp.csproj'
- task: SonarCloudPrepare@1
  displayName: 'Prepare analysis on SonarCloud'
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'mithunnit'
    scannerMode: 'MSBuild'
    projectKey: 'WebAppWithDatabaseDemo-Complete'
- task: DotNetCoreCLI@2
  displayName: Build-Web-App
  inputs:
    command: 'build'
    projects: '**/WebApp.csproj'
    arguments: '--configuration -$(buildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: Run-Unit-Tests
  inputs:
    command: 'test'
    projects: '**/WebApp.UnitTest.csproj'
    arguments: '--configuration -$(buildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
    zipAfterPublish: True
- task: SonarCloudAnalyze@1
  displayName: Run Code Analysis'
- task: SonarCloudPublish@1
  displayName: 'Publish Quality Gate Result'
- task: PublishBuildArtifacts@1
  displayName: 'Publish-Artifact.(WebApp.zip)'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'

- job: Database
  displayName: 'Build Database'
  pool:
    vmImage: 'windows-2019'

steps:
- task: MSBuild@1
  displayName: 'Build solution WebApp.Database.sqlproj'
  inputs:
    solution: 'WebApp.Database/WebApp.Database.sqlproj'
    msbuildArguments: '/p:OutDir=$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact (Dacpac)'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'dacpac'



    
   
